version: '3.8'

services:
  django:
    container_name: hachiko-technique-backend
    build:
      context: .
      dockerfile: Dockerfile.django
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .environment
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    networks:
      - hachiko-network

  postgres-main:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgres-main
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres-main:/var/lib/postgresql/data
    env_file: .environment
    networks:
      - hachiko-network

  telegram-bot:
    container_name: hachiko-telegram-bot
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file: .environment
    depends_on:
      - django
    networks:
      - hachiko-network

networks:
  hachiko-network:
    name: hachiko-technique